name = "atw"
compatibility_date = "2024-04-05"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "atw-db"
database_id = "6c3c472a-40ff-493d-b598-ff3c3664f4b3" # Replace with your D1 database ID in Cloudflare

[[r2_buckets]]
binding = "R2"
bucket_name = "pyanpyan-covers"

# Vars for secrets (API Keys)
[vars]
GEMINI_API_KEY = "" # Set this in Cloudflare Dashboard
